name: SonarAction-SelfHosted
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:
jobs:
  sonar-job:
    environment: test
    runs-on: self-hosted
    steps:
     -  name: Code Checkout  
        uses: actions/checkout@v4
     -  name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
     -  name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
     -  name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
     -  name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        shell: bash  
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=sonar_proj -Dsonar.projectName=sonar_proj -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN