name: SonarAction
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:
jobs:
  sonar-job:
    environment: test
    runs-on: ubuntu-latest
    steps:
     -  name: Code Checkout  
        uses: actions/checkout@v4
     -  name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
     -  name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
     -  name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
     -  name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=sonar_proj

